# Service Account
{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.serviceAccount.name }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
- name: {{ .Values.imagePullSecrets.name }}
{{- end }}
{{- end }}
---
# Role for Service Account
{{- if .Values.serviceAccount.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.serviceAccount.name }}-role
rules:
- apiGroups: [""]
  resources:
{{ toYaml .Values.serviceAccount.coreResources | indent 4 }}
  verbs:
{{ toYaml .Values.serviceAccount.coreVerbs | indent 4 }}
- apiGroups: ["apps"]
  resources:
{{ toYaml .Values.serviceAccount.appsResources | indent 4 }}
  verbs:
{{ toYaml .Values.serviceAccount.appsVerbs | indent 4 }}
{{- end }}
---
# RoleBinding for Service Account
{{- if .Values.serviceAccount.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.serviceAccount.name }}-rb
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.serviceAccount.name }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
